import { Studio } from "../types";

export const MOCK_STUDIOS: Studio[] = [
  {
    id: 's1',
    name: 'Indiranagar Sound Labs',
    description: 'Premier recording studio in Bangalore with high-end acoustics and vintage gear. Perfect for vocal tracking and mixing.',
    location: 'Indiranagar, Bangalore',
    pricePerHour: 2500,
    imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=800&auto=format&fit=crop',
    category: 'music',
    equipment: ['Neumann U87', 'SSL Console', 'Pro Tools Ultimate'],
    amenities: ['Vocal Booth', 'Lounge', 'Coffee Bar'],
    genres: ['Hip Hop', 'Independent', 'Bollywood'],
    rating: 4.9,
    isPremium: true,
  },
  {
    id: 's2',
    name: 'Koramangala Film Floors',
    description: 'Spacious cyclorama wall studio suitable for ad films, fashion shoots, and product photography.',
    location: 'Koramangala, Bangalore',
    pricePerHour: 3500,
    imageUrl: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?q=80&w=800&auto=format&fit=crop',
    category: 'video',
    equipment: ['Arri Alexa Mini', 'Aputure 600d', 'Green Screen'],
    amenities: ['Make-up Room', 'Changing Room', 'Power Backup'],
    genres: ['Commercials', 'Fashion', 'E-commerce'],
    rating: 4.8,
  },
  {
    id: 's3',
    name: 'Whitefield Podcast Hub',
    description: 'Plug-and-play podcasting space with high-quality microphones and video recording capability.',
    location: 'Whitefield, Bangalore',
    pricePerHour: 1200,
    imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=800&auto=format&fit=crop',
    category: 'podcast',
    equipment: ['Shure SM7B', 'Rodecaster Pro II', 'Blackmagic 6K'],
    amenities: ['Soundproof', 'High-speed WiFi', 'Refreshments'],
    genres: ['Business', 'Tech', 'Dialogue'],
    rating: 4.7,
  },
  {
    id: 's4',
    name: 'MG Road Digital Ledger',
    description: 'Iconic digital billboard located at the heart of MG Road for maximum brand visibility.',
    location: 'MG Road, Bangalore',
    pricePerHour: 15000,
    imageUrl: 'https://images.unsplash.com/photo-1542744094-24638eff58bb?q=80&w=800&auto=format&fit=crop',
    category: 'billboard',
    equipment: ['4K LED Display', 'Remote Scheduling'],
    amenities: ['Maintenance', 'Real-time Analytics'],
    rating: 5.0,
    isPremium: true,
  },
  {
    id: 's5',
    name: 'Jayanagar Creative Loft',
    description: 'Natural light studio for lifestyle and organic brand shoots.',
    location: 'Jayanagar, Bangalore',
    pricePerHour: 1800,
    imageUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=800&auto=format&fit=crop',
    category: 'mixed',
    equipment: ['Sony A7R IV', 'Godox AD600 Pro'],
    amenities: ['Natural Light', 'Plant Props', 'Dressing Area'],
    genres: ['Lifestyle', 'Editorial'],
    rating: 4.6,
  },
];

export const INSPIRATION_ITEMS = [
  {
    id: 'i1',
    title: 'Gen Z Skincare Ad',
    type: 'Video',
    previewUrl: 'https://picsum.photos/seed/skincare/400/600',
  },
  {
    id: 'i2',
    title: 'Minimalist Tech Setup',
    type: 'Image',
    previewUrl: 'https://picsum.photos/seed/tech/400/600',
  },
  {
    id: 'i3',
    title: 'Sustainable Fashion Shoot',
    type: 'Inspiration',
    previewUrl: 'https://picsum.photos/seed/fashion/400/600',
  },
];
